// Generates src/generated/locales.ts from the single source of truth
// i18n/locales.toml (SPEC P8: configuration as data, reviewed in diff).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "smol-toml";

const here = dirname(fileURLToPath(import.meta.url));
const tomlPath = resolve(here, "../../i18n/locales.toml");
const outPath = resolve(here, "../src/generated/locales.ts");

const toml = parse(readFileSync(tomlPath, "utf8"));
const active = toml.active ?? [];
const locales = Object.entries(toml.locale ?? {});

const chains = Object.fromEntries(
  locales.map(([id, spec]) => [id, spec.fallback ?? []]),
);

const lines = [
  "// GENERATED by scripts/gen-locales.mjs — do not edit by hand.",
  "// Source of truth: i18n/locales.toml (SPEC P8).",
  "",
  `export const ACTIVE_LOCALES: string[] = ${JSON.stringify(active)};`,
  "",
  "export const LOCALE_CHAINS: Record<string, string[]> = {",
  ...locales.map(
    ([id]) => `  ${JSON.stringify(id)}: ${JSON.stringify(chains[id])},`,
  ),
  "};",
  "",
];

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n"), "utf8");