import { useMemo, useState } from "react";
import { foodGroups, foodsForNutrient, nutrientsCatalog, type FoodGroup, type NutrientInfo, type NutrientRank } from "./search";

export default function QueryLab() {
  const nutrients = useMemo(() => nutrientsCatalog(), []);
  const groups: FoodGroup[] = useMemo(() => foodGroups(), []);
  const [nutrientId, setNutrientId] = useState(nutrients[0]?.id ?? "ENERC_KCAL");
  const [locale, setLocale] = useState("pt-PT");
  const [group, setGroup] = useState("");
  const [min, setMin] = useState("");
  const [max, setMax] = useState("");
  const nutrient: NutrientInfo | undefined = nutrients.find((item) => item.id === nutrientId);
  const ranked = useMemo(() => foodsForNutrient(nutrientId, locale, 100, group || null).filter((food) => (min === "" || (food.value ?? 0) >= Number(min)) && (max === "" || (food.value ?? 0) <= Number(max))), [group, locale, max, min, nutrientId]);
  const download = () => { const body = ["food\tconcept_id\tvalue\tunit", ...ranked.map((food) => `${food.label}\t${food.conceptId}\t${food.value ?? ""}\t${food.unit ?? ""}`)].join("\n"); const url = URL.createObjectURL(new Blob([body], { type: "text/tab-separated-values" })); const link = document.createElement("a"); link.href = url; link.download = `nutridb-${nutrientId.toLowerCase()}.tsv`; link.click(); URL.revokeObjectURL(url); };
  return <div className="content-stack query-page"><div className="page-intro"><div><span className="eyebrow">QUERY LAB / READ-ONLY</span><h2>Ask the dataset sharper questions</h2><p>Build a ranked slice of the matrix without hiding the nutrient code, unit or concept identity.</p></div><button className="ghost-button" onClick={download}>Download TSV -&gt;</button></div><div className="query-layout"><section className="query-builder"><div className="builder-header"><span className="eyebrow">QUERY BUILDER</span><Pill>local SQLite</Pill></div><label>Nutrient<select className="select-control wide" value={nutrientId} onChange={(event) => setNutrientId(event.target.value)}>{nutrients.map((item) => <option key={item.id} value={item.id}>{item.id} · {item.name}</option>)}</select></label><div className="query-fields"><label>Locale<select className="select-control" value={locale} onChange={(event) => setLocale(event.target.value)}><option>pt-PT</option><option>en</option><option>fr</option></select></label><label>Food group<select className="select-control" value={group} onChange={(event) => setGroup(event.target.value)}><option value="">All groups</option>{groups.map((item) => <option key={item.id} value={item.id}>{item.namePt || item.nameEn}</option>)}</select></label></div><div className="query-fields"><label>Minimum value<input className="text-input" type="number" value={min} onChange={(event) => setMin(event.target.value)} placeholder="no minimum" /></label><label>Maximum value<input className="text-input" type="number" value={max} onChange={(event) => setMax(event.target.value)} placeholder="no maximum" /></label></div><div className="query-contract"><span className="eyebrow">QUERY CONTRACT</span><code>WHERE value IS NOT NULL<br />AND basis = 'per_100g_edible'<br />ORDER BY value DESC</code></div></section><section className="query-results"><div className="results-header"><div><span className="eyebrow">RESULT SET</span><h3>{nutrient?.name ?? nutrientId}</h3><small>{nutrientId} · {nutrient?.unit ?? "unit"} · {ranked.length} matching foods</small></div><div className="result-stat"><strong>{ranked[0]?.value?.toLocaleString("pt-PT") ?? "-"}</strong><span>top value</span></div></div><div className="rank-list">{ranked.slice(0, 30).map((food: NutrientRank, index) => <div className="query-result-row" key={`${food.conceptId}-${food.locale}`}><span className="rank-index">{String(index + 1).padStart(2, "0")}</span><div><strong>{food.label}</strong><small>{food.foodGroup} · {food.conceptId}</small></div><b>{food.value?.toLocaleString("pt-PT", { maximumFractionDigits: 3 })} <em>{food.unit}</em></b></div>)}</div></section></div></div>;
}

function Pill({ children }: { children: React.ReactNode }) { return <span className="pill pill-green">{children}</span>; }
