"""Contract tests for the USDA R6 retention factor integration (ADR-0018).

The committed derivations/retention_factors.csv is GENERATED by
scripts/build_retention_factors.py from the pinned official source. These
tests keep the file honest against the derive-stage contract (SPEC §10).
"""

from __future__ import annotations

import csv

import pytest

from nutridb.export import ExportError  # noqa: F401  (ensures module imports clean)
from nutridb.paths import project_root

ROOT = project_root()
FACTORS = ROOT / "derivations" / "retention_factors.csv"
REFERENCE = ROOT / "derivations" / "usda_r6_reference.csv"

HEADER = ("nutrient", "cooking_method", "retention_factor", "evidence")


def _factor_rows() -> list[dict[str, str]]:
    with FACTORS.open(encoding="utf-8") as handle:
        data = [line for line in handle if not line.startswith("#")]
    return list(csv.DictReader(data))


def _vocab_tagnames() -> set[str]:
    lines = [
        line
        for line in (ROOT / "vocab" / "nutrients.csv").open(encoding="utf-8")
        if not line.startswith("#")
    ]
    return {row["tagname"] for row in csv.DictReader(lines)}


@pytest.mark.skipif(not FACTORS.is_file(), reason="retention factors not generated yet")
class TestRetentionFactors:
    def test_header_matches_derive_contract(self) -> None:
        with FACTORS.open(encoding="utf-8") as handle:
            data_lines = [line for line in handle if not line.startswith("#")]
        reader = csv.reader(data_lines)
        assert next(reader) == list(HEADER)

    def test_keys_unique_and_factors_in_range(self) -> None:
        rows = _factor_rows()
        assert len(rows) >= 200
        keys = {(row["nutrient"], row["cooking_method"]) for row in rows}
        assert len(keys) == len(rows)
        for row in rows:
            factor = float(row["retention_factor"])
            assert 0.0 < factor <= 1.0

    def test_all_nutrients_exist_in_vocabulary(self) -> None:
        vocab = _vocab_tagnames()
        unknown = {row["nutrient"] for row in _factor_rows()} - vocab
        assert not unknown

    def test_evidence_cites_doi_and_spread(self) -> None:
        for row in _factor_rows():
            assert "10.15482/USDA.ADC/1409034" in row["evidence"]
            assert "median of" in row["evidence"]
            assert "min" in row["evidence"] and "max" in row["evidence"]

    def test_reference_file_is_full_fidelity(self) -> None:
        assert REFERENCE.is_file()
        with REFERENCE.open(encoding="utf-8") as handle:
            count = sum(1 for _ in handle) - 1
        assert count == 7018

    def test_source_hash_is_pinned_in_header(self) -> None:
        head = FACTORS.read_text(encoding="utf-8")[:800]
        assert "5B71867F6649E801DB3BF88C6CD1887B0673E853D4BA94AA0AF2B3C091E983F9" in head
        assert "CC0" in head
